export {
  digestCliAuthenticationSecret,
  makeCliAuthenticationChallenge,
  makeCliAuthenticationSecret,
  makeCliAuthenticationVerifier,
} from "./cli-authentication-crypto";
export {
  AdminCliAdministrationApi,
  AdminCliApi,
  AdminCliInfo,
  type AdminCliInfo as AdminCliInfoType,
  AdministrationActorUsername,
  type AdministrationActorUsername as AdministrationActorUsernameType,
  AdministrationBookingDetail,
  type AdministrationBookingDetail as AdministrationBookingDetailType,
  AdministrationBookingPage,
  type AdministrationBookingPage as AdministrationBookingPageType,
  AdministrationBookingQuery,
  type AdministrationBookingQuery as AdministrationBookingQueryType,
  AdministrationBookingSummary,
  type AdministrationBookingSummary as AdministrationBookingSummaryType,
  AdministrationCalendarSale,
  type AdministrationCalendarSale as AdministrationCalendarSaleType,
  AdministrationCanonicalPromotionCode,
  type AdministrationCanonicalPromotionCode as AdministrationCanonicalPromotionCodeType,
  AdministrationCustomer,
  type AdministrationCustomer as AdministrationCustomerType,
  AdministrationCustomerActivity,
  type AdministrationCustomerActivity as AdministrationCustomerActivityType,
  AdministrationCustomerCode,
  type AdministrationCustomerCode as AdministrationCustomerCodeType,
  AdministrationCustomerDetail,
  type AdministrationCustomerDetail as AdministrationCustomerDetailType,
  AdministrationCustomerDiscountCodeCreateInput,
  type AdministrationCustomerDiscountCodeCreateInput as AdministrationCustomerDiscountCodeCreateInputType,
  AdministrationCustomerMarketingConsent,
  type AdministrationCustomerMarketingConsent as AdministrationCustomerMarketingConsentType,
  AdministrationCustomerPage,
  type AdministrationCustomerPage as AdministrationCustomerPageType,
  AdministrationCustomerProfile,
  type AdministrationCustomerProfile as AdministrationCustomerProfileType,
  AdministrationCustomerQuery,
  type AdministrationCustomerQuery as AdministrationCustomerQueryType,
  AdministrationCustomerReservationPage,
  type AdministrationCustomerReservationPage as AdministrationCustomerReservationPageType,
  AdministrationCustomerReservationsQuery,
  type AdministrationCustomerReservationsQuery as AdministrationCustomerReservationsQueryType,
  AdministrationCustomerSearchQuery,
  type AdministrationCustomerSearchQuery as AdministrationCustomerSearchQueryType,
  AdministrationCustomerSearchResult,
  type AdministrationCustomerSearchResult as AdministrationCustomerSearchResultType,
  AdministrationCustomerSummary,
  type AdministrationCustomerSummary as AdministrationCustomerSummaryType,
  AdministrationCustomerTransaction,
  type AdministrationCustomerTransaction as AdministrationCustomerTransactionType,
  AdministrationCustomerVoucher,
  type AdministrationCustomerVoucher as AdministrationCustomerVoucherType,
  AdministrationCustomerVoucherCreateInput,
  type AdministrationCustomerVoucherCreateInput as AdministrationCustomerVoucherCreateInputType,
  AdministrationDiscount,
  type AdministrationDiscount as AdministrationDiscountType,
  AdministrationDiscountAdjustment,
  type AdministrationDiscountAdjustment as AdministrationDiscountAdjustmentType,
  AdministrationDiscountApplication,
  type AdministrationDiscountApplication as AdministrationDiscountApplicationType,
  AdministrationDiscountApplicationId,
  type AdministrationDiscountApplicationId as AdministrationDiscountApplicationIdType,
  AdministrationDiscountCode,
  type AdministrationDiscountCode as AdministrationDiscountCodeType,
  AdministrationDiscountCodeClaim,
  type AdministrationDiscountCodeClaim as AdministrationDiscountCodeClaimType,
  AdministrationDiscountCodeClaimId,
  type AdministrationDiscountCodeClaimId as AdministrationDiscountCodeClaimIdType,
  AdministrationDiscountCodeConfigurationInput,
  type AdministrationDiscountCodeConfigurationInput as AdministrationDiscountCodeConfigurationInputType,
  AdministrationDiscountCodeCreateInput,
  type AdministrationDiscountCodeCreateInput as AdministrationDiscountCodeCreateInputType,
  AdministrationDiscountCodeDetail,
  type AdministrationDiscountCodeDetail as AdministrationDiscountCodeDetailType,
  AdministrationDiscountCodeId,
  type AdministrationDiscountCodeId as AdministrationDiscountCodeIdType,
  AdministrationDiscountCodeUpdateInput,
  type AdministrationDiscountCodeUpdateInput as AdministrationDiscountCodeUpdateInputType,
  AdministrationDiscountDashboard,
  type AdministrationDiscountDashboard as AdministrationDiscountDashboardType,
  AdministrationDiscountDefinitionInput,
  type AdministrationDiscountDefinitionInput as AdministrationDiscountDefinitionInputType,
  AdministrationDiscountGroup,
  type AdministrationDiscountGroup as AdministrationDiscountGroupType,
  AdministrationDiscountLabels,
  type AdministrationDiscountLabels as AdministrationDiscountLabelsType,
  AdministrationDiscountMutation,
  type AdministrationDiscountMutation as AdministrationDiscountMutationType,
  AdministrationDiscountMutationResult,
  type AdministrationDiscountMutationResult as AdministrationDiscountMutationResultType,
  AdministrationDiscountUpdateInput,
  type AdministrationDiscountUpdateInput as AdministrationDiscountUpdateInputType,
  AdministrationDotyposCustomerId,
  type AdministrationDotyposCustomerId as AdministrationDotyposCustomerIdType,
  AdministrationDotyposDiscountGroupId,
  type AdministrationDotyposDiscountGroupId as AdministrationDotyposDiscountGroupIdType,
  AdministrationDotyposReservationId,
  type AdministrationDotyposReservationId as AdministrationDotyposReservationIdType,
  AdministrationDotyposTableId,
  type AdministrationDotyposTableId as AdministrationDotyposTableIdType,
  AdministrationExistingDiscountCodeCreateInput,
  type AdministrationExistingDiscountCodeCreateInput as AdministrationExistingDiscountCodeCreateInputType,
  AdministrationExternalCustomer,
  type AdministrationExternalCustomer as AdministrationExternalCustomerType,
  AdministrationGoogleCalendarEventId,
  type AdministrationGoogleCalendarEventId as AdministrationGoogleCalendarEventIdType,
  AdministrationGoogleCalendarICalUid,
  type AdministrationGoogleCalendarICalUid as AdministrationGoogleCalendarICalUidType,
  AdministrationInstant,
  type AdministrationInstant as AdministrationInstantType,
  AdministrationInvoiceCreateFileInput,
  type AdministrationInvoiceCreateFileInput as AdministrationInvoiceCreateFileInputType,
  AdministrationInvoiceCreateInput,
  type AdministrationInvoiceCreateInput as AdministrationInvoiceCreateInputType,
  AdministrationInvoiceCreateResult,
  type AdministrationInvoiceCreateResult as AdministrationInvoiceCreateResultType,
  AdministrationInvoiceCustomerAddress,
  type AdministrationInvoiceCustomerAddress as AdministrationInvoiceCustomerAddressType,
  AdministrationInvoiceCustomerDetails,
  type AdministrationInvoiceCustomerDetails as AdministrationInvoiceCustomerDetailsType,
  AdministrationInvoiceCustomerInput,
  type AdministrationInvoiceCustomerInput as AdministrationInvoiceCustomerInputType,
  AdministrationInvoiceDetail,
  type AdministrationInvoiceDetail as AdministrationInvoiceDetailType,
  AdministrationInvoiceId,
  type AdministrationInvoiceId as AdministrationInvoiceIdType,
  AdministrationInvoiceListItem,
  type AdministrationInvoiceListItem as AdministrationInvoiceListItemType,
  AdministrationInvoicePage,
  type AdministrationInvoicePage as AdministrationInvoicePageType,
  AdministrationInvoicePaymentStatus,
  type AdministrationInvoicePaymentStatus as AdministrationInvoicePaymentStatusType,
  AdministrationInvoicePdf,
  AdministrationInvoiceQuery,
  type AdministrationInvoiceQuery as AdministrationInvoiceQueryType,
  AdministrationInvoiceRetryResult,
  type AdministrationInvoiceRetryResult as AdministrationInvoiceRetryResultType,
  AdministrationInvoiceSort,
  type AdministrationInvoiceSort as AdministrationInvoiceSortType,
  AdministrationMoney,
  type AdministrationMoney as AdministrationMoneyType,
  AdministrationNexiOperation,
  type AdministrationNexiOperation as AdministrationNexiOperationType,
  AdministrationNexiOperationId,
  type AdministrationNexiOperationId as AdministrationNexiOperationIdType,
  AdministrationNexiOrder,
  type AdministrationNexiOrder as AdministrationNexiOrderType,
  AdministrationNexiOrderId,
  type AdministrationNexiOrderId as AdministrationNexiOrderIdType,
  AdministrationOperation,
  type AdministrationOperation as AdministrationOperationType,
  AdministrationOperationDetail,
  type AdministrationOperationDetail as AdministrationOperationDetailType,
  AdministrationOperationList,
  type AdministrationOperationList as AdministrationOperationListType,
  AdministrationOperationQuery,
  type AdministrationOperationQuery as AdministrationOperationQueryType,
  AdministrationOrder,
  type AdministrationOrder as AdministrationOrderType,
  AdministrationOrderLink,
  type AdministrationOrderLink as AdministrationOrderLinkType,
  AdministrationOrderList,
  type AdministrationOrderList as AdministrationOrderListType,
  AdministrationOrderQuery,
  type AdministrationOrderQuery as AdministrationOrderQueryType,
  AdministrationOverview,
  type AdministrationOverview as AdministrationOverviewType,
  AdministrationOverviewMetric,
  type AdministrationOverviewMetric as AdministrationOverviewMetricType,
  AdministrationPaymentAttempt,
  type AdministrationPaymentAttempt as AdministrationPaymentAttemptType,
  AdministrationPaymentAttemptId,
  type AdministrationPaymentAttemptId as AdministrationPaymentAttemptIdType,
  AdministrationReservationAccessGrant,
  type AdministrationReservationAccessGrant as AdministrationReservationAccessGrantType,
  AdministrationReservationAccessMutation,
  type AdministrationReservationAccessMutation as AdministrationReservationAccessMutationType,
  AdministrationReservationCancellationInput,
  type AdministrationReservationCancellationInput as AdministrationReservationCancellationInputType,
  AdministrationReservationCancellationResult,
  type AdministrationReservationCancellationResult as AdministrationReservationCancellationResultType,
  AdministrationReservationDetail,
  type AdministrationReservationDetail as AdministrationReservationDetailType,
  AdministrationReservationLifecycle,
  type AdministrationReservationLifecycle as AdministrationReservationLifecycleType,
  AdministrationReservationLifecycleStage,
  type AdministrationReservationLifecycleStage as AdministrationReservationLifecycleStageType,
  AdministrationReservationLookupQuery,
  type AdministrationReservationLookupQuery as AdministrationReservationLookupQueryType,
  AdministrationReservationLookupResult,
  type AdministrationReservationLookupResult as AdministrationReservationLookupResultType,
  AdministrationReservationPage,
  type AdministrationReservationPage as AdministrationReservationPageType,
  AdministrationReservationQuery,
  type AdministrationReservationQuery as AdministrationReservationQueryType,
  AdministrationReservationSort,
  type AdministrationReservationSort as AdministrationReservationSortType,
  AdministrationReservationSortDirection,
  type AdministrationReservationSortDirection as AdministrationReservationSortDirectionType,
  AdministrationReservationStatusGroup,
  type AdministrationReservationStatusGroup as AdministrationReservationStatusGroupType,
  AdministrationReservationSummary,
  type AdministrationReservationSummary as AdministrationReservationSummaryType,
  AdministrationStoredDiscountId,
  type AdministrationStoredDiscountId as AdministrationStoredDiscountIdType,
  AdministrationTimelineItem,
  type AdministrationTimelineItem as AdministrationTimelineItemType,
  AdministrationVoucher,
  type AdministrationVoucher as AdministrationVoucherType,
  AdministrationVoucherClaim,
  type AdministrationVoucherClaim as AdministrationVoucherClaimType,
  AdministrationVoucherClaimId,
  type AdministrationVoucherClaimId as AdministrationVoucherClaimIdType,
  AdministrationVoucherConfigurationInput,
  type AdministrationVoucherConfigurationInput as AdministrationVoucherConfigurationInputType,
  AdministrationVoucherCreateInput,
  type AdministrationVoucherCreateInput as AdministrationVoucherCreateInputType,
  AdministrationVoucherDetail,
  type AdministrationVoucherDetail as AdministrationVoucherDetailType,
  AdministrationVoucherId,
  type AdministrationVoucherId as AdministrationVoucherIdType,
  AdministrationVoucherUpdateInput,
  type AdministrationVoucherUpdateInput as AdministrationVoucherUpdateInputType,
  AdministrationWorkspaceProductTarget,
  type AdministrationWorkspaceProductTarget as AdministrationWorkspaceProductTargetType,
  AdministrationWorkspaceReservationId,
  type AdministrationWorkspaceReservationId as AdministrationWorkspaceReservationIdType,
  CLI_BUILD_TARGETS,
  CliAccessToken,
  type CliAccessToken as CliAccessTokenType,
  CliAuthenticationChallenge,
  type CliAuthenticationChallenge as CliAuthenticationChallengeType,
  CliAuthenticationCode,
  type CliAuthenticationCode as CliAuthenticationCodeType,
  CliAuthenticationRateLimited,
  CliAuthenticationStatus,
  type CliAuthenticationStatus as CliAuthenticationStatusType,
  CliAuthenticationVerifier,
  type CliAuthenticationVerifier as CliAuthenticationVerifierType,
  CliBearerAuthentication,
  CliBuildTarget,
  type CliBuildTarget as CliBuildTargetType,
  CliClientName,
  type CliClientName as CliClientNameType,
  CliGrantRejected,
  CliGrantToken,
  type CliGrantToken as CliGrantTokenType,
  CliMutationInProgress,
  CliMutationRejected,
  CliMutationRequestId,
  type CliMutationRequestId as CliMutationRequestIdType,
  CliResourceNotFound,
  CliServiceUnavailable,
  CliSession,
  type CliSession as CliSessionType,
  CliSessionAdministration,
  type CliSessionAdministration as CliSessionAdministrationType,
  CliSessionId,
  type CliSessionId as CliSessionIdType,
  CliSessionMutationResult,
  type CliSessionMutationResult as CliSessionMutationResultType,
  CliSessionUnauthorized,
  CurrentCliSession,
  ExchangeCliGrant,
  type ExchangeCliGrant as ExchangeCliGrantType,
  GrantedCliSession,
  type GrantedCliSession as GrantedCliSessionType,
  RenameCliSession,
  type RenameCliSession as RenameCliSessionType,
  StartCliAuthentication,
  type StartCliAuthentication as StartCliAuthenticationType,
  StartedCliAuthentication,
  type StartedCliAuthentication as StartedCliAuthenticationType,
  WORKSPACE_ADMIN_API_VERSION,
  WorkspaceAdminApi,
} from "./workspace-admin-api";
