"use client";

import {
  motion,
  useReducedMotion,
  useScroll,
  useTransform,
} from "motion/react";
import { useRef } from "react";

type LandingPageLocationMapImageProps = {
  alt: string;
  height: number;
  src: string;
  width: number;
};

export function LandingPageLocationMapImage({
  alt,
  height,
  src,
  width,
}: LandingPageLocationMapImageProps) {
  const frameRef = useRef<HTMLDivElement>(null);
  const shouldReduceMotion = useReducedMotion();
  const { scrollYProgress } = useScroll({
    target: frameRef,
    offset: ["start end", "end start"],
  });
  const y = useTransform(scrollYProgress, [0, 1], ["-15%", "15%"]);

  return (
    <div className="absolute inset-0 overflow-hidden" ref={frameRef}>
      {/* biome-ignore lint/performance/noImgElement: This JPEG is generated by an app route; Next/Image cannot optimize it at build time. */}
      <motion.img
        alt={alt}
        className="absolute left-0 -top-[12%] h-[174%] w-full max-w-none object-cover object-center will-change-transform lg:-top-[10%] lg:h-[120%] lg:w-[140%]"
        height={height}
        src={src}
        style={shouldReduceMotion ? undefined : { y }}
        width={width}
      />
    </div>
  );
}
