import type { Locale } from "@/features/i18n";
import { m } from "@/features/i18n";
import { Container } from "@/shared/components/container";
import { Badge } from "@/shared/components/ui/badge";
import { Button } from "@/shared/components/ui/button";
import {
  workspaceFormattedAddress,
  workspaceGoogleDirectionsUrl,
  workspaceLocationMapImageOptions,
  workspaceLocationMapImagePath,
} from "@/shared/utils";

type LandingPageLocationMapSectionProps = {
  locale: Locale;
};

export function LandingPageLocationMapSection({
  locale,
}: LandingPageLocationMapSectionProps) {
  return (
    <section className="relative overflow-hidden bg-[#f4f1ea] text-navy-blue">
      <div className="relative min-h-[26rem] sm:min-h-[30rem] lg:min-h-[34rem]">
        {/* biome-ignore lint/performance/noImgElement: This JPEG is generated by an app route; Next/Image cannot optimize it at build time. */}
        <img
          alt={m.landingLocationMapAlt({}, { locale })}
          className="absolute inset-0 h-full w-full object-cover"
          height={workspaceLocationMapImageOptions.height}
          src={workspaceLocationMapImagePath}
          width={workspaceLocationMapImageOptions.width}
        />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(244,241,234,0.96)_0%,rgba(244,241,234,0.82)_38%,rgba(244,241,234,0.18)_100%)]" />

        <Container className="relative z-10 flex min-h-[26rem] items-end py-8 sm:min-h-[30rem] sm:py-10 lg:min-h-[34rem]">
          <div className="max-w-xl rounded-[2rem] border border-navy-blue/10 bg-[#f4f1ea]/95 p-6 shadow-[0_34px_90px_-55px_rgba(0,2,79,0.75)] backdrop-blur sm:p-8">
            <Badge>{m.landingLocationMapLabel({}, { locale })}</Badge>
            <h2 className="mt-4 text-4xl leading-tight text-balance sm:text-5xl">
              {m.landingLocationMapTitle({}, { locale })}
            </h2>
            <p className="mt-4 text-base leading-8 text-navy-blue/74">
              {m.landingLocationMapLead({}, { locale })}
            </p>
            <address className="mt-6 not-italic text-lg font-semibold leading-7">
              {workspaceFormattedAddress}
            </address>
            <Button
              asChild
              className="mt-7 h-12 px-7 uppercase tracking-[0.08em]"
            >
              <a
                href={workspaceGoogleDirectionsUrl}
                rel="noopener noreferrer"
                target="_blank"
              >
                {m.landingLocationMapCta({}, { locale })}
              </a>
            </Button>
          </div>
        </Container>
      </div>
    </section>
  );
}
