import { defineConfig, type OxlintOverride } from "oxlint";

// Existing anti-slop debt. Remove a path when its suppressed rule is fixed in that file.
// ponytail: file-level baseline; replace with native diagnostic baselining if Oxlint adds it.
const antiSlopBaseline = [
  {
    files: [
      "apps/deskohub-boardgame-bar/app/\\[locale\\]/cookie-settings/page.tsx",
      "apps/deskohub-boardgame-bar/app/api/admin/dotypos/token/route.test.ts",
      "apps/deskohub-workspace/app/workspace-location-map.jpeg/route.test.ts",
      "apps/deskohub-workspace/e2e/cases/meeting-room.test.ts",
      "apps/deskohub-workspace/e2e/checkout/data.test.ts",
      "apps/deskohub-workspace/e2e/checkout/payment.test.ts",
      "apps/deskohub-workspace/e2e/integrations/database.test.ts",
      "apps/deskohub-workspace/e2e/playwright-checkout/run-plan.ts",
      "apps/deskohub-workspace/e2e/playwright-github-summary.test.ts",
      "apps/deskohub-workspace/e2e/preview-readiness.test.ts",
      "apps/deskohub-workspace/e2e/runtime.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout-status.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/cowork-checkout-pricing.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/meeting-room-checkout-pricing.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/pay-state.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/payable-reservation.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/fulfillment/paid-fulfillment.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/fulfillment/resend-webhook.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/holds/reservation-hold-cleanup-queue.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/holds/reservation-hold-cleanup.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/payment/nexi-webhook.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/payment/provider-payment-finalization.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/reservation/dotypos-reservation.adapter.test.ts",
      "apps/deskohub-workspace/features/checkout/checkout-quote.test.ts",
      "apps/deskohub-workspace/features/checkout/components/checkout-pay-page.test.tsx",
      "apps/deskohub-workspace/features/discounts/calculator.test.ts",
      "apps/deskohub-workspace/features/discounts/discount-code.test.ts",
      "apps/deskohub-workspace/features/reservation/actions/prepare-pay-state.test.ts",
      "apps/deskohub-workspace/features/reservation/backend/workspace-reservation.service.test.ts",
      "apps/deskohub-workspace/shared/backend/workspace-action.test.ts",
      "packages/dotypos/src/backend/service.test.ts",
      "packages/i18n/src/effect.ts",
      "packages/nexi/src/backend/service.test.ts",
      "packages/posthog/scripts/generate.ts",
    ],
    rules: { "anti-slop/no-chained-type-assertions": "off" },
  },
  {
    files: [
      ".github/actions/workspace-e2e-allocation/index.mjs",
      "apps/deskohub-workspace/e2e/capacity.ts",
      "apps/deskohub-workspace/e2e/integrations/database.ts",
      "apps/deskohub-workspace/e2e/playwright-checkout/fixtures.ts",
      "apps/deskohub-workspace/e2e/playwright-checkout/run-plan.ts",
      "apps/deskohub-workspace/e2e/services/telemetry.mock.ts",
      "apps/deskohub-workspace/e2e/services/telemetry.ts",
      "apps/deskohub-workspace/e2e/suite.ts",
      "apps/deskohub-workspace/features/accounting/invoice.test-utils.ts",
      "apps/deskohub-workspace/features/checkout/backend/analytics/posthog-lifecycle-events.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout-status.service.ts",
      "apps/deskohub-workspace/features/checkout/backend/fulfillment/workspace-reservation-email.service.tsx",
      "apps/deskohub-workspace/features/checkout/workspace-table-map.ts",
      "apps/deskohub-workspace/features/discounts/admin/discount-administration.service.ts",
      "apps/deskohub-workspace/features/meeting-room/components/meeting-room-page.test.tsx",
      "apps/deskohub-workspace/next.config.mjs",
      "apps/deskohub-workspace/shared/backend/analytics/posthog-event.service.ts",
      "apps/deskohub-workspace/shared/backend/analytics/posthog-request-context.ts",
      "apps/deskohub-workspace/shared/backend/logging/posthog-log-annotations.ts",
      "apps/deskohub-workspace/shared/backend/logging/posthog-otel.ts",
      "apps/deskohub-workspace/shared/backend/observability/otel-tracing.ts",
      "apps/deskohub-workspace/shared/backend/observability/posthog-tracing.ts",
      "apps/deskohub-workspace/shared/backend/observability/workspace-tracing.ts",
      "apps/deskohub-workspace/shared/backend/workspace-action.ts",
      "apps/dhw/src/build.ts",
      "apps/dhw/src/update/github-release.service.ts",
      "apps/dhw/src/update/update.service.ts",
      "packages/dotypos/src/backend/service.ts",
    ],
    rules: { "anti-slop/no-conditional-empty-object-spread": "off" },
  },
  {
    files: [
      "apps/deskohub-boardgame-bar/app/\\[locale\\]/reservation/page.tsx",
      "apps/deskohub-boardgame-bar/features/dotypos/backend/service.test.ts",
      "apps/deskohub-boardgame-bar/features/gallery/components/client-gallery.tsx",
      "apps/deskohub-boardgame-bar/shared/utils/constants.ts",
      "apps/deskohub-boardgame-bar/shared/utils/error-formatting.ts",
      "apps/deskohub-boardgame-bar/shared/utils/geo-formatting.ts",
      "apps/deskohub-boardgame-bar/shared/utils/working-hours-helpers.ts",
      "apps/deskohub-workspace/e2e/runtime.test.ts",
      "apps/deskohub-workspace/e2e/services/telemetry.ts",
      "apps/deskohub-workspace/e2e/suite.ts",
      "apps/deskohub-workspace/env.ts",
      "apps/deskohub-workspace/features/administration/admin-shell.tsx",
      "apps/deskohub-workspace/features/administration/payment-administration.service.ts",
      "apps/deskohub-workspace/features/administration/reservation-date-range.ts",
      "apps/deskohub-workspace/features/administration/reservation-lifecycle-map.tsx",
      "apps/deskohub-workspace/features/checkout/backend/fulfillment/resend-webhook.service.test.ts",
      "apps/deskohub-workspace/features/checkout/product-catalog.i18n.ts",
      "apps/deskohub-workspace/features/checkout/product-catalog.ts",
      "apps/deskohub-workspace/features/checkout/workspace-room-layouts.ts",
      "apps/deskohub-workspace/features/cookie-consent/components/cookie-settings-page.tsx",
      "apps/deskohub-workspace/features/cookie-consent/utils/posthog-url.ts",
      "apps/deskohub-workspace/features/legal/content.tsx",
      "apps/deskohub-workspace/shared/backend/logging/censorship.test.ts",
      "apps/deskohub-workspace/shared/backend/logging/censorship.ts",
      "apps/deskohub-workspace/shared/components/site-header-config.ts",
      "apps/deskohub-workspace/shared/utils/error-formatting.ts",
      "packages/cloudinary-image/src/cloudinary-image.tsx",
      "packages/dotypos/src/backend/service.test.ts",
      "packages/dotypos/src/backend/service.ts",
      "packages/dotypos/src/table-map.tsx",
      "packages/email/backend/escaping.ts",
      "packages/i18n/src/pathname.ts",
      "packages/nexi/src/backend/service.ts",
      "packages/next-effect/src/internal/executor.test.ts",
      "packages/reservation/src/index.ts",
    ],
    rules: { "anti-slop/no-known-value-widening": "off" },
  },
  {
    files: [
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout-session-key.server.ts",
      "apps/deskohub-workspace/shared/utils/error-formatting.ts",
    ],
    rules: { "anti-slop/no-object-parameters": "off" },
  },
  {
    files: [
      ".github/actions/workspace-e2e-allocation/index.mjs",
      "apps/deskohub-boardgame-bar/app/api/admin/dotypos/token/route.ts",
      "apps/deskohub-boardgame-bar/env.ts",
      "apps/deskohub-boardgame-bar/features/analytics/utils/gtm-events.ts",
      "apps/deskohub-boardgame-bar/features/board-games/components/BoardGamesCard.tsx",
      "apps/deskohub-boardgame-bar/features/board-games/components/BoardGamesList.tsx",
      "apps/deskohub-boardgame-bar/features/board-games/utils/sort-games.ts",
      "apps/deskohub-boardgame-bar/features/cookie-consent/components/cookie-consent-provider.tsx",
      "apps/deskohub-boardgame-bar/features/cookie-consent/utils/consent-mode.ts",
      "apps/deskohub-boardgame-bar/features/dotypos/backend/oauth.service.ts",
      "apps/deskohub-boardgame-bar/features/i18n/components/localized-link.tsx",
      "apps/deskohub-boardgame-bar/proxy.test.ts",
      "apps/deskohub-boardgame-bar/shared/backend/utils/effect-safe-action.ts",
      "apps/deskohub-boardgame-bar/shared/utils/currency.ts",
      "apps/deskohub-boardgame-bar/shared/utils/date-formatting.ts",
      "apps/deskohub-boardgame-bar/shared/utils/environment.ts",
      "apps/deskohub-boardgame-bar/shared/utils/error-formatting.ts",
      "apps/deskohub-boardgame-bar/shared/utils/metadata.ts",
      "apps/deskohub-workspace/app/api/workspace/availability/route.ts",
      "apps/deskohub-workspace/e2e/browser.ts",
      "apps/deskohub-workspace/e2e/checkout/data.ts",
      "apps/deskohub-workspace/e2e/checkout/payment.ts",
      "apps/deskohub-workspace/e2e/coordination/allocation.repository.ts",
      "apps/deskohub-workspace/e2e/errors.ts",
      "apps/deskohub-workspace/e2e/integrations/database-operation.ts",
      "apps/deskohub-workspace/e2e/integrations/database.ts",
      "apps/deskohub-workspace/e2e/integrations/invoice-persistence.ts",
      "apps/deskohub-workspace/e2e/playwright-checkout/run-plan.ts",
      "apps/deskohub-workspace/e2e/playwright-checkout/setup.pw.ts",
      "apps/deskohub-workspace/e2e/runtime.ts",
      "apps/deskohub-workspace/env.ts",
      "apps/deskohub-workspace/features/admin-cli/actions.ts",
      "apps/deskohub-workspace/features/administration/page-data.server.ts",
      "apps/deskohub-workspace/features/administration/table-toolbar.tsx",
      "apps/deskohub-workspace/features/checkout/actions/apply-discount-code.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/pay-state.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/replacement-pay-state.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/repositories/payment-lifecycle.repository.ts",
      "apps/deskohub-workspace/features/contact/actions/submit-contact.ts",
      "apps/deskohub-workspace/features/cookie-consent/hooks/use-cookie-consent.ts",
      "apps/deskohub-workspace/features/cookie-consent/utils/consent-event.ts",
      "apps/deskohub-workspace/features/cookie-consent/utils/consent-mode.ts",
      "apps/deskohub-workspace/features/cookie-consent/utils/posthog-url.ts",
      "apps/deskohub-workspace/features/discounts/admin/discount-administration.service.ts",
      "apps/deskohub-workspace/features/discounts/admin/form-feedback.ts",
      "apps/deskohub-workspace/features/discounts/admin/form-input.ts",
      "apps/deskohub-workspace/features/feature-flags/backend/node.test.ts",
      "apps/deskohub-workspace/features/i18n/routing.ts",
      "apps/deskohub-workspace/features/legal/acceptance-snapshot.ts",
      "apps/deskohub-workspace/features/office/components/office-reservation-form.tsx",
      "apps/deskohub-workspace/features/reservation/backend/workspace-availability-replacement.test.ts",
      "apps/deskohub-workspace/features/reservation/components/reservation-date-picker.tsx",
      "apps/deskohub-workspace/features/reservation/components/reservation-date-time-picker.tsx",
      "apps/deskohub-workspace/shared/backend/logging/censorship.ts",
      "apps/deskohub-workspace/shared/backend/logging/posthog-otel.test.ts",
      "apps/deskohub-workspace/shared/backend/observability/posthog-tracing.test.ts",
      "apps/deskohub-workspace/shared/backend/workspace-action.ts",
      "apps/deskohub-workspace/shared/utils/consent-cookie.ts",
      "apps/deskohub-workspace/shared/utils/error-formatting.ts",
      "apps/deskohub-workspace/shared/utils/use-workspace-action.ts",
      "apps/dhw/src/build-info.ts",
      "packages/cloudinary-image/src/cloudinary-image.tsx",
      "packages/cloudinary/src/cache-tags.ts",
      "packages/cloudinary/src/expression.ts",
      "packages/cloudinary/src/service.test.ts",
      "packages/cloudinary/src/service.ts",
      "packages/dotypos/src/backend/service.test.ts",
      "packages/email/backend/providers/console-provider.ts",
      "packages/email/backend/providers/resend-provider.ts",
      "packages/email/backend/service.ts",
      "packages/google-calendar/src/backend/service.ts",
      "packages/i18n/src/translatable.ts",
      "packages/nexi/src/backend/api.ts",
      "packages/posthog/src/feature-flags/node.test.ts",
      "packages/posthog/src/feature-flags/render.ts",
      "packages/posthog/src/feature-flags/sync.ts",
      "packages/standard-schema/src/index.test.ts",
      "packages/standard-schema/src/index.ts",
    ],
    rules: { "anti-slop/no-runtime-typeof": "off" },
  },
  {
    files: [
      "apps/deskohub-boardgame-bar/features/dotypos/backend/oauth.service.ts",
      "apps/deskohub-boardgame-bar/features/dotypos/backend/service.test.ts",
      "apps/deskohub-boardgame-bar/features/dotypos/backend/service.ts",
      "apps/deskohub-boardgame-bar/features/menu/data.ts",
      "apps/deskohub-boardgame-bar/shared/utils/safe-action-client.ts",
      "apps/deskohub-workspace/features/checkout/components/workspace-table-map-view.tsx",
      "apps/deskohub-workspace/shared/backend/workspace-action.ts",
      "apps/deskohub-workspace/shared/utils/safe-action-client.ts",
      "apps/deskohub-workspace/shared/utils/use-workspace-action.ts",
      "packages/dotypos/src/table-map.test.tsx",
      "packages/dotypos/src/table-map.tsx",
      "packages/next-effect/src/effect-action.test.ts",
      "packages/next-effect/src/effect-action.ts",
    ],
    rules: { "anti-slop/no-shape-in-symbol-names": "off" },
  },
  {
    files: [
      "apps/deskohub-boardgame-bar/app/api/admin/dotypos/token/route.test.ts",
      "apps/deskohub-boardgame-bar/app/api/admin/dotypos/token/route.ts",
      "apps/deskohub-boardgame-bar/app/api/webhooks/products/route.test.ts",
      "apps/deskohub-boardgame-bar/features/dotypos/backend/oauth.service.ts",
      "apps/deskohub-boardgame-bar/features/localization/effect-locale.ts",
      "apps/deskohub-boardgame-bar/shared/utils/error-formatting.ts",
      "apps/deskohub-workspace/e2e/browser.ts",
      "apps/deskohub-workspace/e2e/checkout/payment.test.ts",
      "apps/deskohub-workspace/e2e/checkout/payment.ts",
      "apps/deskohub-workspace/e2e/coordination/allocation.repository.ts",
      "apps/deskohub-workspace/e2e/errors.ts",
      "apps/deskohub-workspace/e2e/integrations/invoice-persistence.ts",
      "apps/deskohub-workspace/e2e/playwright-checkout/run-plan.ts",
      "apps/deskohub-workspace/e2e/runtime.test.ts",
      "apps/deskohub-workspace/e2e/runtime.ts",
      "apps/deskohub-workspace/features/admin-cli/page-data.server.ts",
      "apps/deskohub-workspace/features/administration/route-identifiers.server.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout-session-key.server.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout-state-token.ts",
      "apps/deskohub-workspace/features/checkout/backend/fulfillment/resend-webhook.service.ts",
      "apps/deskohub-workspace/features/checkout/backend/holds/reservation-hold-cleanup-queue.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/holds/reservation-hold-cleanup-queue.service.ts",
      "apps/deskohub-workspace/features/checkout/backend/payment/nexi-amount.codec.ts",
      "apps/deskohub-workspace/features/checkout/backend/payment/nexi-webhook.service.ts",
      "apps/deskohub-workspace/features/cowork/components/cowork-reservation-form.test.tsx",
      "apps/deskohub-workspace/features/discounts/admin/form-feedback.ts",
      "apps/deskohub-workspace/features/discounts/contracts.ts",
      "apps/deskohub-workspace/features/discounts/discount-definition.test.ts",
      "apps/deskohub-workspace/features/feature-flags/backend/node.test.ts",
      "apps/deskohub-workspace/features/i18n/server/request-locale.test.ts",
      "apps/deskohub-workspace/features/meeting-room/components/meeting-room-reservation-form.test.tsx",
      "apps/deskohub-workspace/features/reservation/actions/prepare-pay-state.ts",
      "apps/deskohub-workspace/features/reservation/reservation-interval.ts",
      "apps/deskohub-workspace/features/reservation/workspace-availability.ts",
      "apps/deskohub-workspace/shared/backend/logging/censorship.test.ts",
      "apps/deskohub-workspace/shared/backend/logging/censorship.ts",
      "apps/deskohub-workspace/shared/backend/logging/database-query-logger.ts",
      "apps/deskohub-workspace/shared/backend/workspace-action.ts",
      "apps/deskohub-workspace/shared/testing/workspace-component-module-mocks.ts",
      "apps/deskohub-workspace/shared/utils/consent-cookie.ts",
      "apps/deskohub-workspace/shared/utils/error-formatting.ts",
      "apps/deskohub-workspace/shared/utils/schema-parser.ts",
      "apps/deskohub-workspace/shared/utils/temporal.ts",
      "apps/deskohub-workspace/shared/utils/use-workspace-action.ts",
      "packages/cloudinary/src/cache-tags.ts",
      "packages/cloudinary/src/service.ts",
      "packages/dotypos/src/backend/api.ts",
      "packages/dotypos/src/backend/service.test.ts",
      "packages/dotypos/src/backend/service.ts",
      "packages/email/backend/providers/resend-provider.test.ts",
      "packages/email/backend/providers/resend-provider.ts",
      "packages/google-calendar/src/backend/service.test.ts",
      "packages/google-calendar/src/backend/service.ts",
      "packages/i18n/src/effect.ts",
      "packages/nexi/src/backend/api.ts",
      "packages/nexi/src/backend/service.ts",
      "packages/nexi/src/types.ts",
      "packages/next-effect/src/effect-action.ts",
      "packages/next-effect/src/index.ts",
      "packages/posthog/src/feature-flags/node.test.ts",
      "packages/standard-schema/src/index.ts",
    ],
    rules: { "anti-slop/no-unknown-parameters": "off" },
  },
  {
    files: [
      "apps/deskohub-boardgame-bar/app/\\[locale\\]/route.d.ts",
      "apps/deskohub-boardgame-bar/app/api/webhooks/products/route.test.ts",
      "apps/deskohub-boardgame-bar/features/analytics/utils/gtm-events.ts",
      "apps/deskohub-boardgame-bar/shared/utils/defaults.ts",
      "apps/deskohub-boardgame-bar/shared/utils/error-formatting.ts",
      "apps/deskohub-workspace/e2e/browser.ts",
      "apps/deskohub-workspace/e2e/integrations/database.ts",
      "apps/deskohub-workspace/e2e/playwright-checkout/run-plan.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout-status.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/checkout.service.test.ts",
      "apps/deskohub-workspace/features/checkout/backend/checkout/pay-state.test.ts",
      "apps/deskohub-workspace/features/cookie-consent/utils/posthog-event.test.ts",
      "apps/deskohub-workspace/features/cookie-consent/utils/posthog-url.ts",
      "apps/deskohub-workspace/features/discounts/discount-release-gate.service.test.ts",
      "apps/deskohub-workspace/features/discounts/discount.service.test.ts",
      "apps/deskohub-workspace/features/discounts/provider.ts",
      "apps/deskohub-workspace/features/landing-page/landing-page-sale-banner.server.test.ts",
      "apps/deskohub-workspace/shared/backend/analytics/posthog-event.service.ts",
      "apps/deskohub-workspace/shared/backend/logging/censorship.test.ts",
      "apps/deskohub-workspace/shared/backend/logging/censorship.ts",
      "packages/cloudinary/src/cache-tags.ts",
      "packages/cloudinary/src/service.test.ts",
      "packages/dotypos/src/backend/service.test.ts",
      "packages/dotypos/src/backend/service.ts",
      "packages/dotypos/src/table-map.test.tsx",
      "packages/email/types/email.types.ts",
      "packages/google-calendar/src/backend/service.test.ts",
    ],
    rules: { "anti-slop/no-unsafe-dictionary-type": "off" },
  },
] satisfies OxlintOverride[];

export default defineConfig({
  ignorePatterns: ["**/generated/**"],
  jsPlugins: [{ name: "anti-slop", specifier: "./lint/anti-slop/index.ts" }],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
  },
  overrides: antiSlopBaseline,
});
